ALTER TABLE profiles 
    ALTER COLUMN city DROP NOT NULL,
    ALTER COLUMN state DROP NOT NULL,
    ALTER COLUMN country DROP NOT NULL,
    ALTER COLUMN gender DROP NOT NULL,
    ALTER COLUMN bio DROP NOT NULL,
    ALTER COLUMN interested_in DROP NOT NULL,
    ALTER COLUMN relationship_goal DROP NOT NULL;