# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/outty_db
spring.datasource.username=postgres
spring.datasource.password=solo2424

# JWT
jwt.secret=ReplaceWithAVeryLongRandomSecretKeyAtLeast32CharactersLong
jwt.expiration=3600000